exein-io/pulsar

modules/syscall-monitor/src/lib.rs
Syscall monitor added processes to a map but never deleted the old entries. This resulted in a leak.
After every polling cycle, we remove entries not present in the map anymore (exited processes)
=> fix #9: leak in syscall monitor

bpf-common/ProbeTutorial.md
The probe tutorial hasn't been updated after the the `bpf-common` refactor in PR https://github.com/Exein-io/pulsar/pull/5
=> Fix probe tutorial

bpf-common/src/program.rs
=> fix minor typo in comments

modules/network-monitor/src/lib.rs, modules/process-monitor/src/lib.rs, pulsar/examples/probe.rs
This pr simply aims to solve clippy warnings in example binaries and tests
=> fix clippy errors for all binaries and tests

engine-api/src/server.rs, pulsar-core/src/pdk/config.rs, pulsar/src/pulsard/daemon.rs, pulsar/src/pulsard/mod.rs
This pr aims to add custom api socket configuration. it's needed for file systems that doesn't have the required path, for example on Android
=> feat: add custom api socket path

Cargo.lock, bpf-common/Cargo.toml, engine-api/Cargo.toml, modules/file-system-monitor/Cargo.toml, modules/network-monitor/Cargo.toml, modules/process-monitor/Cargo.toml, modules/syscall-monitor/Cargo.toml, pulsar-core/Cargo.toml, pulsar/Cargo.toml, test-suite/Cargo.toml, validatron/Cargo.toml, validatron/derive/Cargo.toml, xtask/Cargo.toml
bpf-common@0.2.0
engine-api@0.2.0
file-system-monitor@0.2.0
network-monitor@0.2.0
process-monitor@0.2.0
pulsar@0.2.0
pulsar-core@0.2.0
syscall-monitor@0.2.0
test-suite@0.2.0
validatron@0.2.0
validatron-derive@0.2.0
xtask@0.2.0
Generated by cargo-workspaces
=> Release 0.2.0

engine-api/src/server.rs
fix unix socket removal on server shutdown
=> fix(api): delete correct unix socket

bpf-common/src/program.rs
This fix adds the probe name as context to most errors.
=> fix(bpf-common): add proper context in program loading

README.md
added some documentation about bpf lsm
=> doc: add bpf lsm details

modules/file-system-monitor/src/lib.rs, pulsar-core/src/event.rs, pulsar-core/src/kernel.rs, pulsar-core/src/lib.rs, pulsar-core/src/platform/linux-aarch64.rs, pulsar-core/src/platform/linux-riscv64.rs, pulsar-core/src/platform/linux-x86_64.rs
Introduction of kernel file flags in event struct
Reference #71
=> Kernel file flags

pulsar/src/pulsard/mod.rs
Add a function to increase rlimit similar to other BPF tools
=> Increase rlimit

.github/workflows/release.yaml, .gitignore
Added a github release workflow adapted from [cloud-hypervisor](https://github.com/cloud-hypervisor/cloud-hypervisor)
=> Release action

.cargo/config.toml, .github/workflows/release.yaml
=> fix release action

.github/workflows/release.yaml, CHANGELOG.md
Changes to the release workflow
Related to #86
=> Release action 2

CHANGELOG.md, Cargo.lock, README.md, bpf-common/Cargo.toml, engine-api/Cargo.toml, modules/file-system-monitor/Cargo.toml, modules/network-monitor/Cargo.toml, modules/process-monitor/Cargo.toml, modules/syscall-monitor/Cargo.toml, pulsar-core/Cargo.toml, pulsar/Cargo.toml, test-suite/Cargo.toml, validatron/Cargo.toml, validatron/derive/Cargo.toml, xtask/Cargo.toml
- Update crates version
- Update README
- Update CHANGELOG
=> prepare for 0.3

pulsar-install.sh
Update file names in the installer script according to the release workflow
=> Installer script: update download file names

rules/basic-rules.yaml
=> Basic rules

README.md, bpf-common/ProbeTutorial.md
=> fix broken links in readme

bpf-common/src/bpf_fs.rs, modules/file-system-monitor/src/lib.rs, modules/logger/src/lib.rs, modules/network-monitor/src/lib.rs, modules/process-monitor/src/lib.rs, modules/rules-engine/src/lib.rs, modules/syscall-monitor/src/lib.rs, pulsar-core/src/event.rs
- Removed debug print message
- Update versions in modules
- Added `from()` for `Argv`
=> Cosmetics fixes

Cargo.lock, test-suite/Cargo.toml, test-suite/src/main.rs
Refactor test-suite binary to use a backgrounnd async test-runner.
Fix #107
=> misc(test-suite): upgrade to libtest-mimic 0.6

.github/workflows/audit.yaml, .github/workflows/build.yaml, .github/workflows/quality.yaml, CONTRIBUTING.md
=> md links check

bpf-common/src/parsing/procfs.rs, engine-api/src/client.rs, modules/process-monitor/src/lib.rs, pulsar/src/pulsar/mod.rs
simply fixes last `clippy` warnings
=> fix clippy warnings

Cargo.lock, Cargo.toml, modules/desktop-notifier/Cargo.toml, modules/desktop-notifier/README.md, modules/desktop-notifier/src/lib.rs, pulsar/Cargo.toml, pulsar/src/lib.rs
Fix #41 by creating a new [desktop-notifier module](https://github.com/Exein-io/pulsar/tree/desktop-notifier/modules/desktop-notifier)
=> Add desktop-notifier module

crates/bpf-common/ProbeTutorial.md, crates/bpf-common/src/parsing/procfs.rs, crates/bpf-common/src/program.rs, crates/bpf-common/src/test_runner.rs, crates/bpf-common/src/trace_pipe.rs, crates/engine-api/src/client.rs, crates/engine-api/src/error.rs, crates/modules/network-monitor/src/lib.rs, crates/modules/process-monitor/src/filtering/maps.rs, crates/modules/process-monitor/src/lib.rs, crates/validatron/src/parser.rs, examples/pulsar-module-as-library/main.rs, src/cli/mod.rs, src/pulsard/config.rs, xtask/src/main.rs
- fixes clippy 1.67 warnings
- fix broken markdown links using branch relative
=> clippy 1.67 warnings

crates/engine-api/src/server.rs, crates/pulsar-core/src/pdk/module.rs, src/pulsar/mod.rs
fix client disconnection for event monitor
=> event monitor fix

Cargo.lock, Cargo.toml
update version for the 0.5.0 release
=> update version to 0.5.0

CHANGELOG.md, README.md, crates/pulsar-core/src/event.rs
- pulsar threat log in root readme
- changelog for version 0.5.0
=> Readme and changelog update

crates/bpf-common/src/feature_autodetect/kernel_version.rs
=> fix parse_uname_release for wsl2

.cross/README.md, .cross/aarch64-unknown-linux-gnu.Dockerfile, .cross/aarch64-unknown-linux-musl.Dockerfile, .cross/riscv64gc-unknown-linux-gnu.Dockerfile, .cross/x86_64-unknown-linux-gnu.Dockerfile, .cross/x86_64-unknown-linux-musl.Dockerfile
Simply update `Clang/LLVM` to **16** in `cross` configuration
=> Update clang to version 16

README.md, crates/bpf-common/src/feature_autodetect/lsm.rs, src/pulsard/module_manager.rs, test-suite/src/test_suite_runner.rs
- Improve module stop command handling, in particular for the `Created` state
- readme changes/fix example rule
- remove debug print in lsm try attach
=> Small fixes

crates/validatron/derive/src/lib.rs, crates/validatron/src/lib.rs, crates/validatron/src/reflection.rs
Small fixes in the documentation to make tests working
=> fix doctest in validatron crate

.github/workflows/build.yaml, .github/workflows/quality.yaml, .github/workflows/release.yaml, Cargo.toml
Changes to the CI to support openssl in the next PR #201  .
The idea is to have a more granular configuration depending on the target.
There is also a minor change to use cross everywhere; in this way we have only to maintain the cross dockerfiles, without touching the workflow for system dependencies.
=> CI - Openssl feature setup

Cargo.toml, crates/modules/logger/src/lib.rs, crates/modules/smtp-notifier/Cargo.toml, crates/modules/smtp-notifier/README.md, crates/modules/smtp-notifier/src/lib.rs
Cleanings for `smtp-notifier`, in particular about `openssl`
=> Clean smtp notifier

Cargo.lock, crates/engine-api/Cargo.toml
fixes https://github.com/Exein-io/pulsar/security/dependabot/7
=> fix tungstenite security fix

crates/bpf-builder/include/buffer.bpf.h, crates/bpf-builder/include/common.bpf.h, crates/bpf-builder/include/compatibility.bpf.h, crates/bpf-builder/include/get_path.bpf.h, crates/bpf-builder/include/interest_tracking.bpf.h, crates/bpf-builder/include/iov_iter_compat.h, crates/bpf-builder/include/loop.bpf.h, crates/bpf-builder/include/output.bpf.h, crates/bpf-common/ProbeTutorial.md, crates/bpf-common/src/feature_autodetect/test_lsm.bpf.c, crates/modules/file-system-monitor/probes.bpf.c, crates/modules/network-monitor/probes.bpf.c, crates/modules/process-monitor/probes.bpf.c
- Set GPL inside every probe
- Set GPL header in source files
=> License fix

.github/workflows/build.yaml
For the whole workspace and for all architectures.
=> ci: Run unit tests

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/bpf-common/src/bpf_fs.rs, crates/validatron/derive/Cargo.toml
version and changelog update as preparation for 0.7.0 release
=> prepare for 0.7.0 release

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/validatron/derive/Cargo.toml
update `Cargo.toml`s and `CHANGELOG.md`
=> prepare for 0.7.1 release

crates/bpf-common/src/parsing/mountinfo.rs, crates/bpf-common/src/parsing/procfs.rs, crates/validatron/README.md
=> chore: fix clippy 1.76 warnings

.github/workflows/quality.yaml, README.md
replace `markdown-link-check` with [lychee](https://github.com/lycheeverse/lychee)
=> Use lychee as link checker in CI

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/validatron/derive/Cargo.toml
update changelog and Cargo.toml
=> chore: prepare for 0.8.0 release

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/validatron/derive/Cargo.toml
adjust version and changelog for release
=> prepare for 0.8.1 release

crates/bpf-common/src/trace_pipe.rs
=> allow unused field in tracepipe StopHandle

crates/modules/logger/src/lib.rs
Add syslog priority to fix #280
=> [logger-module] Add syslog priority

crates/modules/desktop-notifier/src/lib.rs, crates/modules/file-system-monitor/src/lib.rs, crates/modules/logger/src/lib.rs, crates/modules/network-monitor/src/lib.rs, crates/modules/process-monitor/src/lib.rs, crates/modules/rules-engine/src/lib.rs, crates/modules/smtp-notifier/src/lib.rs, crates/pulsar-core/src/pdk/module.rs, examples/pulsar-embedded-agent/proxy_module.rs, examples/pulsar-extension-module/my_custom_module.rs, src/pulsard/module_manager.rs
PR implementing the changes suggested in https://github.com/exein-io/pulsar/pull/288#issuecomment-2139915751.
=> Refactored PulsarModule trait

.github/ISSUE_TEMPLATE/BUG-REPORT.yaml
setting me as default assignee for the issue
=> change default assignee in issue template

crates/bpf-common/src/containers/layers.rs, crates/bpf-common/src/containers/mod.rs
Use libpod's image store and layer store to determine image layer directories on the host for Podman.
=> feat: Detect image layer directories for Podman

Cargo.lock, crates/engine-api/src/error.rs, crates/modules/desktop-notifier/src/lib.rs, crates/modules/file-system-monitor/src/lib.rs, crates/modules/logger/src/lib.rs, crates/modules/network-monitor/src/lib.rs, crates/modules/process-monitor/src/lib.rs, crates/modules/rules-engine/src/engine.rs, crates/modules/rules-engine/src/lib.rs, crates/modules/smtp-notifier/src/lib.rs, crates/pulsar-core/Cargo.toml, crates/pulsar-core/src/pdk/daemon.rs, crates/pulsar-core/src/pdk/mod.rs, crates/pulsar-core/src/pdk/module.rs, crates/pulsar-core/src/pdk/module_context.rs, examples/pulsar-embedded-agent/main.rs, examples/pulsar-embedded-agent/proxy_module.rs, examples/pulsar-extension-module/main.rs, examples/pulsar-extension-module/my_custom_module.rs, src/lib.rs, src/main.rs, src/pulsar/term_print.rs, src/pulsard/daemon.rs, src/pulsard/mod.rs, src/pulsard/module_manager.rs
This PR is a copy of #286 and is created as a workaround to fix the the issue described in:
https://github.com/orgs/community/discussions/27521 
Ref: #286
=> (GH Issue #27521 Workaround) Module api refactoring gh pr issue

crates/modules/file-system-monitor/README.md, crates/modules/file-system-monitor/src/lib.rs
`file-system-monitor`: renaming `elf_check_enabled` configuration to `elf_check`
=> rename elf check configuration

.github/workflows/release.yaml
Add `pulsar-install.sh` on releases from tag
=> add pulsar-install.sh for tag releases

.github/workflows/release.yaml
update download artifact to `v4`
=> fix update download artifact

crates/bpf-common/src/containers/layers.rs, crates/bpf-common/src/containers/mod.rs, crates/bpf-features/src/lib.rs, crates/bpf-filtering/src/initializer.rs, crates/bpf-filtering/src/test_suite.rs, crates/engine-api/src/client.rs, crates/engine-api/src/error.rs, crates/modules/smtp-notifier/src/lib.rs, crates/pulsar-core/src/pdk/daemon.rs, crates/validatron/src/validator.rs, src/pulsar/mod.rs, xtask/src/vmlinux.rs
=> chore: Fix clippy errors

crates/modules/file-system-monitor/probes.bpf.c
@paolo9921 discovered a verifier issue in `file-system-monitor` probes with some older kernel versions.
apparently the verifier loose tracks of kernel pointers.
moving `make_path` as first instruction seems to solve the problem.
=> fix `make_path` verifier error restructuring bpf program

crates/bpf-filtering/src/config.rs, crates/modules/desktop-notifier/src/lib.rs, crates/modules/file-system-monitor/README.md, crates/modules/file-system-monitor/src/lib.rs, crates/modules/rules-engine/src/lib.rs, crates/modules/smtp-notifier/src/lib.rs, crates/modules/threat-logger/src/lib.rs, crates/pulsar-core/src/pdk/config.rs, examples/pulsar-extension-module/my_custom_module.rs, src/pulsard/daemon.rs
- swap configuration access method `with_default` with a more explicit `optional` method
- `elf_check` default to `false`
=> improve optional configuration fields
