exein-io/pulsar

modules/syscall-monitor/on_sys_enter.bpf.c
modules/syscall-monitor/src/lib.rs
pulsar-core/src/event.rs

The calls field contained the timestamp of the last time a particular
syscall was invoked. It was never really used, so we've decided to
remove it.

misc(syscall): remove calls field

---

bpf-common/src/test_runner.rs
bpf-common/src/trace_pipe.rs
modules/network-monitor/src/lib.rs
pulsar-core/src/pdk/module.rs
pulsar/examples/probe.rs
pulsar/src/pulsard/daemon.rs

Sometimes the network monitor TCP-close tests failed because the close
event may come from different processes:
- The original process which created the connection
- Pid 0
- Process ksoftirqd
I've removed the PID check from the test case.
I've cleaned up TestRunner:
- `Check::new` is generic and allows a shorter construction
- Added `TestRunner::expect_custom_event` for special cases like the one
described above.
- Moved Check constructors to `TestRunner` because the timestamp one
needed start and end time.

fix(network): fix sporadic close test failures

---

pulsar-core/src/pdk/module.rs

Modules initialization functions need to be Send, but have no real need
to be Sync.
I found this out while developing a module which contained a `!Sync` variable.
_Short introduction explaining the motivation and reasoning behind the pull request._
_Feel free to include design and implementation for external review outside of the code changes._

fix: remove unnecessary Sync from modules future

---

validatron/src/dsl.lalrpop
validatron/src/parser.rs

add list type handling in the rule engine dsl
added list at the parser level

add list type to dsl

---

pulsar-core/src/event.rs

Removing `threshold` field from `AnomalyDetection` and `MalwareDetection` events to implement `score` as the difference between the original score and the model threshold.

Remove threshold from anomaly and malware events

---

modules/process-monitor/src/filtering/maps.rs

`maps::Image::to_string()` formatted the bytes of the process
name as numbers instead of characters. This caused a failure
when initializing `map_interest` in modules/process-monitor/src/filtering/initializer.rs
```
let whitelist_match = self
.config
.whitelist
.iter()
.find(|r| r.image.to_string() == process.image);
let targets_match = self
.config
.targets
.iter()
.find(|r| r.image.to_string() == process.image);
```
_Short introduction explaining the motivation and reasoning behind the pull request._
_Feel free to include design and implementation for external review outside of the code changes._

fix(filtering): regression when initializing filter

---

Cargo.lock
modules/process-monitor/Cargo.toml
modules/process-monitor/src/lib.rs

Instead of using a hardwired path "/usr/bin/echo" which
fails on some distributiones (ex. RHEL8), lookup the path
for 'echo' and use the resolved path for the check in test.
Below is the current test failure with the trunk (branch `main`) version.
Fixes #28.
Signed-off-by: Dmitry Savintsev <dsavints@gmail.com>
```
running 8 tests
test tests::exec_event ... FAILED
test tests::exit_cleans_up_resources ... ok
test tests::exec_updates_interest ... ok
test tests::exit_event ... ok
test tests::exit_event_no_thread ... ok
test tests::fork_event ... ok
test tests::inherit_policy ... ok
test tests::threads_are_ignored ... ok
failures:
---- tests::exec_event stdout ----
[INFO  bpf_common::trace_pipe] Logging events from /sys/kernel/debug/tracing/trace_pipe
1116747336537749 1320995 forked from …
```

Test in modules/process-monitor - lookup echo path

---

validatron/Cargo.toml

Currently building in other projects can cause compilation errors due to missing imports similar to the ones described here - https://github.com/lalrpop/lalrpop/issues/650.
```
bhargav@bhargav-kk:/mnt/c/bhargav/Programming/Language-stuff/brim$ cargo run
Compiling libc v0.2.116
...
Compiling lalrpop v0.19.7
Compiling brim v0.1.0 (/mnt/c/bhargav/Programming/Language-stuff/brim)
error[E0432]: unresolved import `self::__lalrpop_util::lexer`
--> /mnt/c/bhargav/Programming/Language-stuff/brim/target/debug/build/brim-9358516eba536307/out/grammar.rs:22:31
|
22 |     use self::__lalrpop_util::lexer::Token;
|                               ^^^^^ could not find `lexer` in `__lalrpop_util`
...
For more information about an error, try `rustc --explain E0432`.
error: could not compile `brim` due to 5 …
```

Update `lalrpop-util` to include `lexer` feature

---

README.md
bpf-common/Cargo.toml
bpf-common/src/feature_autodetect/lsm.rs
bpf-common/src/feature_autodetect/mod.rs
bpf-common/src/lib.rs
bpf-common/src/parsing/data_array.rs
bpf-common/src/program.rs
bpf-common/src/test_runner.rs
bpf-common/src/trace_pipe.rs
modules/file-system-monitor/probe.bpf.c
modules/file-system-monitor/src/lib.rs
modules/network-monitor/probes.bpf.c
modules/network-monitor/src/lib.rs
modules/process-monitor/probes.bpf.c
modules/process-monitor/src/lib.rs
pulsar-core/src/event.rs
test-suite/Cargo.toml
test-suite/README.md
test-suite/src/main.rs
vagrant/.gitignore
vagrant/static.sh
vagrant/ubuntu2204/Vagrantfile

This PR replace Kprobes with LSM and tracepoints where possible.
- We [autodetect LSM support](https://github.com/Exein-io/pulsar/pull/56/files#diff-a8ae8336058aa3893a9f6d1c63ec04831c4f3f6b78dc0ad7ab676a5ec18b67b7) and [fallback to kprobes](https://github.com/Exein-io/pulsar/pull/56/files#diff-1547f532a7c21f359c4193b6f730b4929e84a35990dddffe49355802708116a7R29-R36) when it's not available.
- File-system-monitor was fully refactored to use LSM hooks
- Network-monitor was refactored to use a combination of LSM hooks and syscalls. [See in-depth explaination](https://github.com/Exein-io/pulsar/pull/56/files#diff-34c932019d747e6110c8c57a102f4b35c475ae2df73e1556407fc5c2bb647053R14-R47).
- Process-monitor kprobe usage was removed by using raw tracepoints.
- Except for fallbacks, the only kprobe …

Replace Kprobes with LSM and tracepoints where possible

---

Cargo.lock
engine-api/Cargo.toml

current version of axum have a cve; this pr simply updates the the latest

misc: update axum dependency to address a cve

---

bpf-common/include/common.bpf.h
modules/file-system-monitor/probe.bpf.c
modules/file-system-monitor/src/lib.rs
modules/network-monitor/probes.bpf.c
pulsar-core/src/event.rs
vagrant/README.md

Hook into LSM `path_rename`, `path_rmdir`, `path_mkdir`, `path_link` and `path_symlink`. As usual, we use kprobes as a fallback.
Fix #64 and #67 
I fixed bug #11 by using the LSM hooks accepting a path argument. This requires the `CONFIG_SECURITY_PATH` config variable.
Unify the two path extraction functions to require a `struct path*`.

File system monitor improvements

---

modules/file-system-monitor/probe.bpf.c
modules/network-monitor/probes.bpf.c
modules/network-monitor/src/lib.rs
modules/process-monitor/probes.bpf.c
modules/process-monitor/src/filtering/initializer.rs
modules/process-monitor/src/lib.rs
pulsar-core/src/event.rs
pulsar-core/src/pdk/module.rs
pulsar-core/src/pdk/process_tracker.rs

This implements #65 and #66
I'm not particularly happy about the performance implications of the arguments modification.
1. We're copying much data on every event to userspace, even if the arguments are smaller.
We should optimize these by using some variable size data structure.
2. We're cloning the arguments when getting info from process tracker https://github.com/Exein-io/pulsar/blob/c39136b3ad8862cb1882833fec2d78bbba958df7/pulsar-core/src/pdk/process_tracker.rs#L269
Even when most of the times we'll discard them: https://github.com/Exein-io/pulsar/blob/c39136b3ad8862cb1882833fec2d78bbba958df7/pulsar-core/src/pdk/module.rs#L184-L191
We could (A) add a different method, complicating the API or (B) use an Arc. What do you think?

Add listen event and exec arguments

---

modules/process-monitor/probes.bpf.c
modules/process-monitor/src/lib.rs

This PR fixes a warning (issue #74) introduced by https://github.com/Exein-io/pulsar/pull/69, which was causing trailing empty arguments.
Note: we're still getting warnings when argument list truncation happens (see #73)

Process-monitor: fix warnings in argument extraction

---

Cargo.lock
pulsar/Cargo.toml
pulsar/src/cli/mod.rs
pulsar/src/cli/pulsar.rs

refactor: update to clap 4. Closes #72

---

modules/network-monitor/probes.bpf.c
modules/network-monitor/src/lib.rs
pulsar-core/src/event.rs

Extract protocol type for bind and connect events.
Listen, accept and close are TCP only, so I've added no field there.
Fix https://github.com/Exein-io/pulsar/issues/79

Add protocol field to bind and connect

---

.github/workflows/build.yaml
.github/workflows/quality.yaml
Cross.toml
bpf-common/src/builder.rs

Add `llvm-strip`  command to strip debug symbols but leaving BTF

Strip BPF probes

---

modules/process-monitor/src/lib.rs
pulsar-core/src/event.rs
pulsar-core/src/kernel.rs

- Introduce `Argv` custom type as a temporary workaround to support agrv based rules
- Fix `FileFlags` comparison

Event type improvements

---

.cross/README.md
.cross/aarch64-unknown-linux-gnu.Dockerfile
.cross/aarch64-unknown-linux-musl.Dockerfile
.cross/riscv64gc-unknown-linux-gnu.Dockerfile
.cross/x86_64-unknown-linux-gnu.Dockerfile
.cross/x86_64-unknown-linux-musl.Dockerfile
Cross.toml
vagrant/fedora36/Vagrantfile

Added a custom container for builds using `cross` with updated `clang/llvm` (v15), the default `clang/llvm` (v10) seems to have problem generating the BPF bytecode.

Custom container for cross builds

---

bpf-common/src/builder.rs
modules/network-monitor/src/lib.rs
modules/process-monitor/src/filtering/maps.rs
modules/rules-engine/src/engine.rs
pulsar/src/pulsard/config.rs
validatron/src/engine.rs

small fixes around to address clippy warnings

fix clippy 1.65 warnings

---

README.md
modules/file-system-monitor/README.md
modules/network-monitor/README.md
modules/process-monitor/README.md

The latest website changes resulted in some dead links.
I also fixed the path reference to `probe.rs`
I used this command for highlighting the issues:
```
markdown-link-check -q $(git ls-files '*.md')
```
I would be cool to enable these checks in CI.

Fix dead links

---

Cargo.lock
engine-api/Cargo.toml
engine-api/src/server.rs

I was reading the latest [Axum release notes](https://tokio.rs/blog/2022-11-25-announcing-axum-0-6-0) and I wanted to give it a try.
- upgraded the dependency
- replaced the non type-safe Extension with the type-safe State
- replaced the Arc around EngineAPIContext with a "derive Clone" since the inner PulsarDaemonHandle is already Clone
- we may decide to [add double routes to support trailing slashes](https://tokio.rs/blog/2022-11-25-announcing-axum-0-6-0#trailing-slash-redirects-removed). I don't think it's needed since only pulsar cli will interact with these URLs.

Upgrade to axum 0.6

---

modules/rules-engine/src/engine.rs
modules/rules-engine/src/lib.rs

Fix  #123  by changing the rule engine to check if threat info are already present in events before starting its analysis

fix(rule_engine): add check for events already marked as threats

---

Cargo.lock
engine-api/Cargo.toml
engine-api/src/client.rs
engine-api/src/error.rs
engine-api/src/server.rs
modules/logger/src/lib.rs
pulsar/Cargo.toml
pulsar/src/cli/pulsar.rs
pulsar/src/pulsar/mod.rs
pulsar/src/pulsard/daemon.rs
pulsar/src/pulsard/mod.rs
validatron/Cargo.toml

Fix #78 adding a command `monitor` for the pulsar cli to print events (default only the threats)  
events are sent over websocket from the server

cli realtime monitor

---

.gitignore
scripts/check_bytecode.sh
scripts/gen_compile_commands.sh

Add a script which compiles a probe and uses llvm-objdump to output
its annotated bytecode. This is useful during development to understand
what compiler optimizations are happening and possible verifier
complaints.
Example:
```
./scripts/check_bytecode.sh modules/file-system-monitor/probe.bpf.c
```
Added a script which generates a `compile_commands.json` for all
eBPF sources. This is useful for auto-completion and error reporting.
We can't simply add the file to git because it contains absolute paths.
This was tested with vscode and the clangd language server of nvim.
Example:
```
./scripts/gen_compile_commands.sh
```

Add scripts to ease development

---

bpf-common/src/program.rs
modules/process-monitor/README.md
modules/process-monitor/src/filtering/config.rs
modules/process-monitor/src/filtering/initializer.rs
modules/process-monitor/src/filtering/maps.rs

Fix #128 by whitelisting the current process path instead of the current PID. This allows to ignore the client CLI executable. Failing to ignore it would lead to loops of events, see issue #128 for more details.
Add option `process-monitor.ignore_self`, which can be used to disable this default behaviour.

new(filtering): whitelist current executable

---

Cargo.lock
bpf-common/Cargo.toml
modules/logger/Cargo.toml

- Update  `chrono` dep to remove default features and only include  feature;
- Update  `procfs` dep to remove default features
Added `cargo audit` which now passes.

Update `chrono`/`procfs` to remove vulnerable `time` dependency

---

bpf-common/ProbeTutorial.md
bpf-common/src/test_runner.rs
modules/file-system-monitor/src/lib.rs
modules/process-monitor/src/lib.rs
pulsar/src/bin/probe.rs

Remove the need to implement Display on inner types of modules:
- Since it had no access to buffer, it was mostly useless as it lacked information.
- Replace its use with IntoPayload for the `probe` binary
- Replace its use with Debug for the test-suite

misc(probe): remove Display from inner events

---

modules/process-monitor/probes.bpf.c
modules/process-monitor/src/filtering/initializer.rs
modules/process-monitor/src/lib.rs
pulsar-core/src/event.rs
pulsar-core/src/pdk/process_tracker.rs

Fix #106
Add a `ChangeParent { ppid: Pid }` event to process monitor, which can be used to intercept when the parent of a process changes.
It works by adding to a temporary map all the orphans of dead processes. This is done by the `collect_orphans` call at the end of `sched_process_exit`. Than we wait for their parent to be changed by the kernel and emit events for the new parents. Ideally we would have done it on the exit of the exit syscall, unfortunately that syscall never returns as the process has died. The kernel will just schedule the next process. For this reason we'll do this check on sched_switch.

Track parent changes

---

vagrant/static.sh
xtask/src/main.rs
xtask/src/run.rs

Fixed a couple of regressions in xtask execution:
- After the new workspace setup, we need to specify the package for the non main crates (eg. test-suite).
- The `cmd!` macro parses its format string: the old code was putting the arguments in the executable name.
- Remove `last` from `run_args` so we don't need the `--` separator.
As an improvement, we're now taking the cargo binary location from the CARGO env variable.

fix(xtask): fix regressions

---

crates/bpf-common/ProbeTutorial.md
crates/modules/desktop-notifier/src/lib.rs
crates/modules/file-system-monitor/src/lib.rs
crates/modules/logger/src/lib.rs
crates/modules/network-monitor/src/lib.rs
crates/modules/process-monitor/src/lib.rs
crates/modules/rules-engine/src/lib.rs
crates/pulsar-core/src/pdk/mod.rs
examples/pulsar-embedded-agent/proxy_module.rs
examples/pulsar-extension-module/my_custom_module.rs
src/pulsard/config.rs

Currently the version in pulsar modules is a fixed string inside every crate and it needs an update at every version change. this pr replaces the fixed string with the crate version.

Better modules version 

---

Cargo.lock
crates/bpf-common/Cargo.toml

update aya now supporting btf kind enum64

---

crates/bpf-common/src/program.rs
crates/modules/logger/src/lib.rs

- align event datetime print to env_logger
- add check for already used map in bpf program

Small fix and change

---

Cargo.lock
crates/bpf-common/Cargo.toml
crates/bpf-common/include/common.bpf.h
crates/bpf-common/include/loop.bpf.h
crates/bpf-common/src/builder.rs
crates/bpf-common/src/feature_autodetect/kernel_version.rs
crates/bpf-common/src/feature_autodetect/mod.rs
crates/bpf-common/src/program.rs
crates/modules/desktop-notifier/src/lib.rs
crates/modules/file-system-monitor/Cargo.toml
crates/modules/file-system-monitor/probe.bpf.c
crates/modules/network-monitor/Cargo.toml
crates/modules/process-monitor/Cargo.toml
crates/modules/process-monitor/probes.bpf.c
crates/pulsar-core/Cargo.toml

Fix #142 by using `bpf_loop`:
- Add kernel version autodetection
- Sent the kernel version as a global variable into the eBPF
- Added a LOOP macro which uses `bpf_loop` when available (kernel >= 5.17) and falls back to an unrolled loop if not.  
- Replaced the loop inside `file-system-monitor` with the new code.

Use bpf_loop when available

---

Cargo.lock
src/pulsard/mod.rs
xtask/Cargo.toml
xtask/src/main.rs

xtask now will drop term signals and depends on the behavior of the sub processes

drop term signals on xtask

---

.gitattributes
crates/bpf-builder/include/loop.bpf.h
crates/bpf-builder/src/lib.rs
crates/bpf-common/ProbeTutorial.md
crates/bpf-common/src/bump_memlock_rlimit.rs
crates/bpf-common/src/feature_autodetect/lsm.rs
crates/bpf-common/src/lib.rs
crates/bpf-common/src/program.rs
crates/modules/file-system-monitor/src/lib.rs
crates/modules/network-monitor/src/lib.rs
crates/modules/process-monitor/src/lib.rs
src/pulsard/mod.rs
test-suite/src/test_suite_runner.rs

Fix https://github.com/Exein-io/pulsar/issues/158 by compiling and embedding two eBPF programs:
- On kernel >= 5.13 we'll use the same code as before
- On kernel < 5.13 we'll compile a version with `NOLOOP` defined.
This requires https://github.com/Exein-io/pulsar/pull/156 to be merged first.

Fix bpf_loop regression on kernel < 5.13

---

crates/modules/network-monitor/probes.bpf.c

This fixes protocol reading (UDP vs TCP) on kernel < 5.6, where sk_protocol was a bitfield and was being incorrectly read.
See https://github.com/Exein-io/pulsar/issues/163

fix(network-monitor): read sk_protocol as a bitfield

---

crates/bpf-builder/include/get_path.bpf.h
crates/bpf-builder/include/loop.bpf.h
crates/bpf-builder/src/lib.rs
crates/modules/file-system-monitor/probes.bpf.c
crates/modules/process-monitor/probes.bpf.c
crates/modules/process-monitor/src/lib.rs
scripts/check_bytecode.sh

Fix process-monitor to always get the absolute file path on exec.
Before this change executing a file with a relative path would have resulted in an exec event with path `./executable`. After this change it will be `/path/to/executable`.
Since the code to extract the full file path is quite complex, we'll execute it only when needed.

Make sure to extract absolute file paths on exec

---

Cargo.lock
Cargo.toml
crates/validatron/Cargo.toml
xtask/Cargo.toml

- fix clippy 1.69 warnings
- update some libraries to remove warnings

clippy 1.69

---

Cargo.lock
crates/bpf-builder/include/output.bpf.h
crates/bpf-common/src/program.rs
crates/modules/process-monitor/Cargo.toml
crates/modules/process-monitor/probes.bpf.c
crates/modules/process-monitor/src/lib.rs
crates/pulsar-core/src/event.rs

Added cgroup integration inside process-monitor.
I've decided to split work on #13 in two PRs, this is the simplest one, while in the next one I'll work on filtering.
|tracepoint|event generated|
|-------------------|------------------------------------|
|`cgroup_mkdir`| `Payload::CgroupCreated`|
|`cgroup_rmdir`|`Payload::CgroupDeleted`|
|`cgroup_attach_task`|`Payload::CgroupAttach`|
I've successfully tested it on x86_64 (5.5 and 5.19) and aarch64 (6.0)

Emit cgroup events from process-monitor

---

rules/basic-rules.yaml

This pr adds `cron` daemon exception to 'Read sensitive file' rule. There are different implementation of `cron`, we are covering:
- `vixie-cron` fork of Debian for Debian like distributions
- `cronie` for RedHat like distributions and SLES

add cron exception to 'Read sensitive file' rule

---

Cargo.lock
crates/bpf-builder/include/get_path.bpf.h
crates/bpf-builder/include/output.bpf.h
crates/bpf-common/Cargo.toml
crates/modules/file-system-monitor/src/lib.rs
crates/modules/process-monitor/probes.bpf.c
crates/pulsar-core/src/platform/linux-aarch64.rs
crates/pulsar-core/src/platform/linux-riscv64.rs
crates/pulsar-core/src/platform/linux-x86_64.rs

Fix #148
This PR replaces manual loops with the LOOP macro inside process-monitor.
~~Blocked by https://github.com/aya-rs/aya/issues/601~~

misc(process-monitor): use bpf_loop in orphans collection

---

crates/bpf-builder/include/compatibility.bpf.h
crates/bpf-builder/include/loop.bpf.h
crates/bpf-builder/include/output.bpf.h
crates/bpf-builder/src/lib.rs
crates/bpf-common/src/feature_autodetect/lsm.rs
crates/bpf-common/src/program.rs
crates/modules/file-system-monitor/probes.bpf.c
crates/modules/file-system-monitor/src/lib.rs
crates/modules/network-monitor/probes.bpf.c
crates/modules/network-monitor/src/lib.rs
crates/modules/process-monitor/probes.bpf.c
crates/modules/process-monitor/src/lib.rs
test-suite/src/test_suite_runner.rs

eBPF programs could interrupt each other, see "Are BPF programs preemptible?" thread on the kernel BPF mailing list:
https://lore.kernel.org/bpf/878rhty100.fsf@cloudflare.com/T/#t

Preemption refactor

---

crates/modules/desktop-notifier/src/lib.rs
crates/modules/logger/src/lib.rs
crates/modules/rules-engine/src/engine.rs
crates/pulsar-core/src/event.rs
crates/pulsar-core/src/pdk/module.rs
examples/pulsar-extension-module/my_custom_module.rs

In the proprietary code-base we've encountered the issue where the extra data introduced in Threat::value or Payload::Custom::value could lead to extremely verbose output. In order to make is easier to read, we've introduced a `description` field, which contains a human-readable description of the threat.

refactor(event): add description field

---

vagrant/static.sh

This way we don't require having the musl toolchain installed on host.

chore(vagrant): Use cross to build pulsar

---

Cargo.lock
Cargo.toml
crates/bpf-common/Cargo.toml
crates/bpf-common/src/platform/linux-aarch64/mod.rs
crates/bpf-common/src/platform/linux-armeabi/mod.rs
crates/bpf-common/src/platform/linux-riscv64/mod.rs
crates/bpf-common/src/platform/linux-x86/mod.rs
crates/bpf-common/src/platform/linux-x86_64/mod.rs
crates/bpf-common/src/test_runner.rs
src/lib.rs

Removes lazy static from the crate and uses OnceLock instead of lazy_static!
resolves #187

[187] Drop Lazy Static And Use Once Cell

---

crates/pulsar-core/src/pdk/daemon.rs
crates/pulsar-core/src/pdk/mod.rs
crates/pulsar-core/src/pdk/module.rs
crates/pulsar-core/src/pdk/module_context.rs
src/pulsar/term_print.rs
src/pulsard/module_manager.rs

Allow modules to show warnings
Uses ctx to allow adding a warning to running status
resolves #32

[32] Allow modules to show warnings

---

crates/bpf-builder/src/lib.rs

This option is not suppoted in BPF target, but some clang 16 installations try to enable it by default. Make sure it's always disabled.

build: Disable stack protector

---

.cross/README.md
.cross/aarch64-unknown-linux-gnu.Dockerfile
.cross/aarch64-unknown-linux-musl.Dockerfile
.cross/riscv64gc-unknown-linux-gnu.Dockerfile
.cross/x86_64-unknown-linux-gnu.Dockerfile
.cross/x86_64-unknown-linux-musl.Dockerfile
Cargo.lock
crates/modules/rules-engine/src/engine.rs
crates/pulsar-core/Cargo.toml
crates/pulsar-core/src/event.rs

This pr introduces a new `PayloadDiscriminant` type to capture the rule `type` field. 
Rulesets are stored per discriminant and tested after having checked the discriminant.
It also improves performances in case there are a lot of rules defined on a single payload type, because not these rules won't be checked for other types
Fix: #210

rule_engine: check payload dicriminant before ruleset

---

Cargo.lock
crates/bpf-filtering/Cargo.toml
crates/bpf-filtering/src/initializer.rs
crates/bpf-filtering/src/process_tree.rs
crates/modules/process-monitor/probes.bpf.c
crates/modules/process-monitor/src/lib.rs
crates/pulsar-core/src/event.rs
crates/pulsar-core/src/pdk/module.rs
crates/pulsar-core/src/pdk/process_tracker.rs

This is a preparatory change for supporting container monitoring in Pulsar. Containers are just set of namespaces, so the easiest way to recognize that a process belongs to a particular container from information available from BPF programs, is to do that based on namespaces.
For now, we simply add information about all namespaces for each executed or forked process.

feat(process-monitor): Include information about namespaces

---

Cargo.lock
Cargo.toml
crates/bpf-builder/Cargo.toml
crates/bpf-common/Cargo.toml
crates/bpf-filtering/Cargo.toml
crates/engine-api/Cargo.toml
crates/modules/desktop-notifier/Cargo.toml
crates/modules/file-system-monitor/Cargo.toml
crates/modules/logger/Cargo.toml
crates/modules/network-monitor/Cargo.toml
crates/modules/process-monitor/Cargo.toml
crates/modules/rules-engine/Cargo.toml
crates/modules/smtp-notifier/Cargo.toml
crates/pulsar-core/Cargo.toml
crates/validatron/Cargo.toml
crates/validatron/derive/Cargo.toml
test-suite/Cargo.toml
xtask/Cargo.toml

Use workspace-defined dependencies to avoid version differences across crates.

chore: Define dependencies in workspace

---

src/pulsard/daemon.rs

Before this change, it was showing for all modules, even the ones only being created, but not started.

fix: Show the "Starting module" message only if it's actually starting

---

crates/modules/desktop-notifier/README.md
crates/modules/desktop-notifier/src/lib.rs
crates/modules/file-system-monitor/src/lib.rs
crates/modules/logger/src/lib.rs
crates/modules/network-monitor/src/lib.rs
crates/modules/process-monitor/src/lib.rs
crates/modules/rules-engine/src/lib.rs
crates/modules/smtp-notifier/README.md
crates/modules/smtp-notifier/src/lib.rs
crates/pulsar-core/src/pdk/module.rs
examples/pulsar-embedded-agent/proxy_module.rs
examples/pulsar-extension-module/my_custom_module.rs
src/pulsard/daemon.rs

Before this change, empty config of Pulsar was resulting in all modules being enabled. It's quite inconvenient in case of smtp-notifier, which requires additional configuration in order to work without errors, and desktop-notifier, which isn't meant for servers. Both of these modules are not going to be used by most of people.
This change adds the `enabled_by_default` flag to `ModuleDetails` which has to be defined by every module. For all modules except smtp-notifier, it's set to `true`.

feat: Make it clear which modules are enabled by default

---

Cargo.lock
crates/modules/logger/Cargo.toml
crates/modules/logger/README.md
crates/modules/logger/src/lib.rs
crates/pulsar-core/Cargo.toml
crates/pulsar-core/src/event.rs
src/pulsar/mod.rs

Add syslog capabilities
resolves #38

Add syslog capabilities

---

Cargo.lock
crates/bpf-common/Cargo.toml
crates/bpf-common/src/parsing/containers.rs
crates/bpf-common/src/parsing/mod.rs
crates/bpf-common/src/parsing/procfs.rs
crates/bpf-common/src/program.rs
crates/bpf-filtering/src/initializer.rs
crates/modules/process-monitor/Cargo.toml
crates/modules/process-monitor/probes.bpf.c
crates/modules/process-monitor/src/lib.rs
crates/pulsar-core/src/event.rs
crates/pulsar-core/src/pdk/module.rs
crates/pulsar-core/src/pdk/process_tracker.rs

Enhance the process monitor with an ability to detect when a
container runtime creates a new mount namespace, which we can consider
as a creation of a new container.
Achieve that by:
* Registering the inodes of container runtime binaries we want to
track in the user-space, saving them in a BPF map.
* In BPF, every time a process is being executed using the runtime
binary, checking whether the PID namespace was changed.

feat(process-monitor): Detect new containers

---

crates/pulsar-core/src/event.rs

Include it in regular events too.

fix: Include container info header not only for threat alerts

---

.github/workflows/release.yaml

this should solve the ci issue we got with the latest tag, where a container was created for the specified tag but a `latest` container was not

fix(ci): latest release tag

---

crates/bpf-common/src/parsing/containers.rs
crates/bpf-common/src/parsing/procfs.rs
crates/bpf-filtering/src/process_tree.rs
crates/pulsar-core/src/pdk/process_tracker.rs

Always check whether a detected process belongs to a container-related cgroup. This way we ensure that we are adding container info even when the container was created before Pulsar was launched.

fix: Handle containers which were running before Pulsar

---

crates/modules/rules-engine/src/dsl.lalrpop
crates/modules/rules-engine/src/dsl.rs

This PR fixes the issue of parsing one character strings in the rule engine DSL

rule engine dsl: fix one char value

---

.github/docker/Dockerfile
.github/docker/Dockerfile.dockerignore
crates/bpf-common/src/parsing/mountinfo.rs
crates/modules/rules-engine/src/dsl.lalrpop
crates/modules/rules-engine/src/dsl.rs
crates/modules/rules-engine/src/engine.rs
crates/pulsar-core/src/event.rs
crates/pulsar-core/src/pdk/mod.rs
crates/pulsar-core/src/pdk/module.rs
crates/validatron/README.md
crates/validatron/examples/struct.rs
crates/validatron/src/builtins.rs
crates/validatron/src/compiler.rs
crates/validatron/src/error.rs
crates/validatron/src/lib.rs
crates/validatron/src/operators.rs
crates/validatron/src/reflection.rs
crates/validatron/src/reflection/adt.rs
crates/validatron/src/reflection/collection.rs
crates/validatron/src/reflection/methods.rs
crates/validatron/src/reflection/primitive.rs
crates/validatron/src/reflection/structure.rs
crates/validatron/src/validator.rs
pulsar-install.sh
rules/container-rules.yaml

This PR adds the folowing features:
- methods call in dsl
- unary expression in dsl
The final goal is to be able to check the following expression as condition:
```
header.container_info.is_some()
```
This PR also want to add full support for `Option<T>` fields. The syntax to access a field of an optional type is for example:
```
header.container?.image == "archlinux"
```

rule-engine: support methods and unary expressions in rules dsl

---

.github/workflows/release.yaml

Fix `latest` container image push in git tag workflow

fix(ci): latest container image push on tag

---

crates/bpf-builder/include/strncmp.bpf.h
crates/modules/process-monitor/probes.bpf.c

This PR should fix #259 providing an alternative implementation for kernel < `5.17`

strncmp implementation for old kernels

---

rules/container-rules.yaml

Common ways to escape the container:
* chroot
* loading kernel modules

chore(rules): Add more generic container rules

---

.gitignore
crates/modules/process-monitor/probes.bpf.c

- add `.vagrant` to `.gitignore`
- log error for missing kernel `CONFIG_MEMCG` flag

Minor changes

---

crates/bpf-filtering/src/filtering_example.bpf.c
crates/bpf-filtering/src/test_suite.rs

The test was failing because of an update of aya on how it access bpf function inside the bpf probe

fix filtering test

---

Cargo.lock
Cargo.toml

We can finally use it without git.

chore: Update to aya 0.12.0

---

crates/modules/network-monitor/probes.bpf.c

Pulsar IOT was not successfully generating DNS queries/answers information. 
First the amount of data read is now corresponding to the data len - 1 in the packet (excl IP and UDP headers). Review is welcome on this point since that does not work if "len = output->data_len" (i.e. the exact size of the data in the packet) but with "len = output->data_len - 1".
For the data reception, destination address retrieval of the incoming packet is skipped. Actually we do not really care about this adress since it should be an adress of one of the network interface...

fix(network-filter): DNS event generation

---

crates/bpf-builder/include/loop.bpf.h
crates/bpf-builder/include/strncmp.bpf.h

Checking kernel version is not the most reliable way of determining whether a given BPF feature is present in the kernel. Many distributions backport BPF features to older kernel versions.
Kernel provides the `enum bpf_func_id` which contains `BPF_FUNC_*` variants. In combination with `bpf_core_enum_value_exists`, it can be used to determine whether the given function is supported by the running kernel.
Fixes: #261

refactor: Replace `LINUX_KERNEL_VERSION` checks with checks on `bpf_func_id`

---

pulsar-install.sh

We already include riscv64gc binaries in releases, so we can also use them in the install script.

chore: Include riscv64gc in pulsar-install.sh

---

Cargo.lock
crates/modules/logger/Cargo.toml
crates/modules/logger/README.md
crates/modules/logger/src/lib.rs

Issue: https://github.com/exein-io/pulsar/issues/264
This feature allows threat reporting to be output as JSON. Output format can be configured via `pulsar.ini` or at runtime with `pulsar config --set logging.output_format=...`. The default output format is `plaintext` to match the current behavior.
Example JSON output of a file creation threat (from the README):
```json
{"header":{"image":"/usr/bin/ln","pid":36738,"parent_pid":12810,"container":null,"threat":{"source":"rules-engine","description":"Create sensitive files symlink","extra":null},"source":"file-system-monitor","timestamp":{"secs_since_epoch":1713625327,"nanos_since_epoch":832828392},"fork_time":{"secs_since_epoch":1713625327,"nanos_since_epoch":818390681}},"payload":{"type":"FileLink","content":{"source":"/tmp/secret","destin …
```

feat: allow threats to be logged as JSON

---

.github/workflows/build.yaml
.github/workflows/quality.yaml

Doing so before was necessary because of `ring` builds failing on RISC-V, but that's not the case anymore.

chore: Stop excluding xtask in RISC-V builds

---

crates/bpf-builder/include/compatibility.bpf.h
crates/bpf-builder/include/loop.bpf.h
crates/bpf-builder/include/output.bpf.h
crates/bpf-common/src/feature_autodetect/kernel_version.rs
crates/bpf-common/src/lib.rs
crates/bpf-common/src/parsing/procfs.rs
crates/bpf-filtering/src/initializer.rs
crates/bpf-filtering/src/process_tree.rs
crates/modules/process-monitor/probes.bpf.c
crates/modules/process-monitor/src/lib.rs
crates/pulsar-core/src/event.rs
crates/pulsar-core/src/pdk/module.rs
crates/pulsar-core/src/pdk/process_tracker.rs

Started to work on #97:
- Added user and group id on fork event (using `bpf_get_current_uid_gid()`)
- Added hooks to intercept credentials change:
- On LSM-supported kernels,`task_fix_set*id` calls are used
- On kernel >= 5.10, we fall back on `security_task_fix_set*id`
- On older kernels we fall back to commit_creds kprobe
- Testing on [architest](https://github.com/Exein-io/architest/releases/tag/0.3) virtual machines led me to discover some regression to to previous pull requests. I've fixed them and all tests are passing now.
- update process-tracker with the user id
- put those into header on event generation
To completely fix #97, the only item left is to:
- ~~add a mapping in process-tracker from user-id to username~~ <sup>not planned in this PR</sup>
A small explanation on …

Get user and group id related events

---

.cross/aarch64-unknown-linux-musl.Dockerfile
.cross/x86_64-unknown-linux-musl.Dockerfile
.github/workflows/build.yaml
.github/workflows/quality.yaml
.github/workflows/release.yaml
Cargo.lock
Cargo.toml
crates/modules/smtp-notifier/Cargo.toml

Introduce the new `static` feature which not only makes all dependencies vendored, but also prefers rustls over OpenSSL. The new underlying features, allowing the choice of TLS implementation, are `tls-openssl` and `tls-rustls`.
OpenSSL is still the default choice when not providing any features.
Since features in Cargo are additive, the `static` feature works properly only with `--no-default-features`. Therefore, the recommended way of performing the static builds is:
```
cross build --target=<triple>-musl --no-default-features --features static
```
Fixes #281

build: Prefer rustls over OpenSSL for static builds

---

crates/pulsar-core/src/event.rs

Fix the implementation of `std::fmt::Display` for `Event` removing the additional blank line

fix event display format

---

.github/release-assets/pulsar-install.sh
.github/workflows/release.yaml
CONTRIBUTING.md
Cargo.toml
README.md
crates/bpf-builder/include/compatibility.bpf.h
crates/modules/smtp-notifier/src/template.html.leon
crates/pulsar-core/src/pdk/module.rs
examples/pulsar-extension-module/README.md
examples/pulsar-module-as-library/README.md

Fix #185 by adding the installer to every release.
The installer now contains a variable `PULSAR_VERSION` that will be populated by the CI

bundle the installer in the release

---

crates/engine-api/src/error.rs
crates/modules/desktop-notifier/src/lib.rs
crates/modules/file-system-monitor/src/lib.rs
crates/modules/logger/src/lib.rs
crates/modules/network-monitor/src/lib.rs
crates/modules/process-monitor/src/lib.rs
crates/modules/rules-engine/src/lib.rs
crates/modules/smtp-notifier/src/lib.rs
crates/pulsar-core/src/pdk/daemon.rs
crates/pulsar-core/src/pdk/module.rs
examples/pulsar-embedded-agent/proxy_module.rs
examples/pulsar-extension-module/my_custom_module.rs
src/pulsard/daemon.rs
src/pulsard/module_manager.rs

Add support for an extra function operating on the state.
The function needs a `trigger` (a `Future`) and an `action` (another `Future`). Under the hood they are used in a `tokio::select!` in the main loop of a module similar to this:
```rust
loop {
tokio::select! {
// ...
out = trigger() => {
action(out).await;
}
// ...
}
}
```
> **Note:** This is a simplified version of the loop, please refer to the code for more details

modules api: support for an extra function working the state

---

.github/workflows/integration.yaml

We noticed CI failures related to lack of ability to fetch packages. Refreshing the repository metadata with `apt-get update` should fix that.

ci: Call `apt-get update` before installing any packages

---

crates/bpf-feature-autodetect/src/func.rs
crates/bpf-feature-autodetect/src/lib.rs

in case of  errors in function probing `feature_autodetect` is showing a message like this:
```console
[2024-06-18T12:43:03Z WARN  bpf_feature_autodetect::func] Function 181 in program type BPF_PROG_TYPE_KPROBE not supported: Failed to load the eBPF feature probe: 0: R1=ctx(off=0,imm=0) R10=fp0
0: (85) call bpf_loop#181
R2 !read_ok
processed 1 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
``` 
this pr wants to reduce the output if backtrace is not enabled limiting the warning to one line

chore: improve func autodetect error message

---

crates/modules/process-monitor/probes.bpf.c

Reviewing #293 I noticed a potential issue with the signature of the function `get_container_info`.
The above mentioned PR changes are the following:
```diff
- static __always_inline int get_container_info(struct task_struct *cur_tsk, char *buf, size_t sz, int *offset)
+ static __always_inline int get_container_info(struct task_struct *cur_tsk,
char *buf, int *offset)
```
The new version assumes that `char *buf` is big at least `CONTAINER_ID_MAX_BUF` using this size in bpf helpers, but this is not true just looking at the signature.
The old version it's not free of issue: it takes the `size_t sz` from the caller and safely use this size in the helpers. In general this approach is fine, it's the correct way of use it but in this case we need the buffer at least of size 72. Now we rely on …

Container id buffer struct

---

crates/bpf-builder/include/buffer.bpf.h
crates/modules/network-monitor/probes.bpf.c
crates/modules/network-monitor/src/lib.rs

* User-space part of pulsar is expecting the buffer to be initialized regardless of L4 protocol (TCP or UDP).
* DNS responses, if long enough, might go through TCP. Not very common, but possible.
* Stop returning an error when packet payload length is 0. It's totally normal for SYN, SYN-ACK and ACK packets. Logging errors for them is an unnecessary noise.
Fixes #297

fix(network-monitor): Include the packet payload regarless of L4 protocol

---

crates/bpf-feature-autodetect/build.rs
crates/bpf-feature-autodetect/src/bpf_loop.rs
crates/bpf-feature-autodetect/src/lib.rs
crates/bpf-feature-autodetect/src/test_bpf_loop.bpf.c

The previously used ASM probe didn't work reliably on new kernels, which were rejecting the program, because of lack of valid function pointer being used as a callback.
Introduce a small C probe which has a minimal, but valid `bpf_loop` call.
Fixes #300

feat: Improved `bpf_loop` probe

---

crates/bpf-builder/include/buffer.bpf.h
crates/bpf-builder/include/get_path.bpf.h
crates/modules/file-system-monitor/probes.bpf.c
crates/modules/process-monitor/probes.bpf.c

The format of cgroup path is different for systemd and cgroupfs drivers.
For systemd driver, it's
```
0::/system.slice/docker-d4ea646fc22c701dbb146e52db4e9125dcca2eebb2f5552f90fedbb28a0f0716.scope
```
For cgroupfs driver, it's
```
0::/docker/2cf2e0be458a80acb354c953f7bb03de5d2d277dfcb8ebaa6575f95668a0c15f
```
Handle both formats.

fix: Docker container ID parsing with cgroupfs driver

---

rules/lateral_movement/telnet_network_activity.yaml

This PR wants to remove a wrong telnet rule.
The rule was about `telnet` but for `Accept` payload

remove wrong telnet rule

---

xtask/src/test.rs

The main motivation is the ability to specify a pattern for tests to run together with architest. Example command:
```
cargo xtask test --target x86_64-unknown-linux-musl \
--features all-vendored --features tls-rustls \
--kernel-versions 6.3 --force-architest \
-- dns
```

test: Allow to provide arguments through `cargo xtask test`

---

Cargo.lock
Cargo.toml
crates/bpf-common/src/test_runner.rs
crates/modules/network-monitor/Cargo.toml
crates/modules/network-monitor/src/lib.rs

Add test cases for DNS requests which use dns-mock-server[0], look for the related network events and try to parse them.
Move `parse_dns` function out of `mod pulsar`, so it can be used in tests.

test: Add an integration test for DNS requests

---

crates/validatron/src/reflection.rs

clippy 1.80

---

Cargo.lock
crates/bpf-common/Cargo.toml
crates/bpf-common/src/containers/layers.rs
crates/bpf-common/src/containers/mod.rs
crates/pulsar-core/src/pdk/process_tracker.rs

For each container, try to retrieve information about image layers paths (from the host filesystem's perspective) and include them in `ContainerInfo`.

feat: Include list of image layer directories in `ContainerInfo`

---

Cargo.lock
Cargo.toml
crates/modules/README.md
crates/modules/threat-logger/Cargo.toml
crates/modules/threat-logger/README.md
crates/modules/threat-logger/src/lib.rs
src/pulsard/mod.rs

Fixes #310 renaming `logger` to `threat-logger` in a consistent way

threat logger module rename

---

crates/modules/file-system-monitor/probes.bpf.c

~~On newer kernel you need to specify the full signature, even if you don't use for last parameters~~
Ref: #318

fix path rename signature

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/validatron/derive/Cargo.toml

- update changelog
- update version

prepare for 0.9.0 release

---

.github/workflows/release.yaml

Fix #329 
Refactor the release workflow to upload the vendored archive, each binary and each docker image to a unique artifact

upload files to unique artifacts

---

.github/workflows/release.yaml

use pattern in download artifact

fix update download artifact 2

---

crates/engine-api/src/client.rs
crates/engine-api/src/error.rs

Improve errors in engine_api [#326](https://github.com/exein-io/pulsar/issues/326)
(this is my second time trying to contribute, feedback is welcome)

Improve error handling in engine_api client using thiserror. Fixes #326

---

src/pulsard/daemon.rs

right now if a module uses methods on `PulsarDaemonHandle` in its `init_state` method it will cause a lock in the initialization because the `PulsarDaemon` actor is not running yet.
a solution is to start the modules asynchronously

fix module start lock

---

.github/release-assets/pulsar-install.sh

When installing Pulsar on a riscv64 architecture using the command:
```bash
curl --proto '=https' --tlsv1.2 -LsSf https://github.com/exein-io/pulsar/releases/latest/download/pulsar-install.sh | sh
```
the following error occurs: 
```bash 
pulsar-install: command failed: downloader https://github.com/exein-io/pulsar/releases/download/v0.9.0/pulsar-execriscv64gc /tmp/tmp.ibEXkx/pulsar-exec
```
This is caused by a missing dash (-) in the architecture string inside function 'get_release_variant()' in pulsar-install.sh.
This fix adds the missing dash to the riscv64 architecture string, resolving the issue.

Fix: add missing dash in riscv64 architecture string

---

.github/workflows/integration.yaml
crates/modules/network-monitor/probes.bpf.c
crates/modules/network-monitor/src/lib.rs

- add lvh as another way to run integration tests
- endianess error on l3 protocol
- incorrect l4 protocol userspace mapping

evaluate lvh for integration tests

---

Cargo.lock
xtask/Cargo.toml
xtask/src/surun.rs

This PR want to solve an issue that happens for example hitting CTRL-C on `xtask::surun` cmd. Right now when the child process doesn't terminate or needs more time the parent (xtask process) exits anyway giving you back the prompt and leaving the child process in background.
Here I changed how the signals are handled, only forwarding signals to the child process but keeping the parent waiting until the child process exits

better handling signals in xtask surun

---

crates/pulsar-core/src/event.rs

This PR removes the legacy `SyscallActivity` event type

chore: remove SyscallActivity event type
